//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionSupportSystem.DataAccessLayer.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class crit_valueSet
    {
        public int Id { get; set; }
        public int person_id { get; set; }
        public double value { get; set; }
    
        public virtual alternativeSet alternativeSet { get; set; }
        public virtual crit_scaleSet crit_scaleSet { get; set; }
        public virtual criteriaSet criteriaSet { get; set; }
    }
}
