//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionSupportSystem.DataAccessLayer.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DcsDataModelContainer : DbContext
    {
        public DcsDataModelContainer()
            : base("name=DcsDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alternativeSet> alternativeSet1 { get; set; }
        public virtual DbSet<crit_scaleSet> crit_scaleSet1 { get; set; }
        public virtual DbSet<crit_valueSet> crit_valueSet1 { get; set; }
        public virtual DbSet<criteriaSet> criteriaSet1 { get; set; }
        public virtual DbSet<taskSet> taskSet1 { get; set; }
    }
}
