//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionSupportSystem.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class crit_scaleSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crit_scaleSet()
        {
            this.crit_valueSet = new HashSet<crit_valueSet>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public double rank { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crit_valueSet> crit_valueSet { get; set; }
        public virtual criteriaSet criteriaSet { get; set; }
    }
}
