//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionSupportSystem.DataAccessLayer.DataCreationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alternative
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alternative()
        {
            this.firstAlternative = new HashSet<PairAlternative>();
            this.SecondAlternative = new HashSet<PairAlternative>();
            this.alternativePriorityVector = new HashSet<AlternativePriorityVector>();
        }
    
        public long id { get; set; }
        public long taskId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string value { get; set; }
    
        public virtual Task task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PairAlternative> firstAlternative { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PairAlternative> SecondAlternative { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlternativePriorityVector> alternativePriorityVector { get; set; }
    }
}
