//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionSupportSystem.DataAccessLayer.DataCreationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlternativePriorityVector
    {
        public long id { get; set; }
        public long alternativeId { get; set; }
        public string value { get; set; }
    
        public virtual Alternative alternative { get; set; }
    }
}
