//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionSupportSystem.DataAccessLayer.DataCreationModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DecisionSupportSystemDataBaseModelContainer : DbContext
    {
        public DecisionSupportSystemDataBaseModelContainer()
            : base("name=DecisionSupportSystemDataBaseModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Task> TaskSet { get; set; }
        public virtual DbSet<Criteria> CriteriaSet { get; set; }
        public virtual DbSet<Alternative> AlternativeSet { get; set; }
        public virtual DbSet<PairAlternative> PairAlternativeSet { get; set; }
        public virtual DbSet<PairCriteria> PairCriteriaSet { get; set; }
        public virtual DbSet<CriteriaPriorityVector> CriteriaPriorityVectorSet { get; set; }
        public virtual DbSet<AlternativePriorityVector> AlternativePriorityVectorSet { get; set; }
    }
}
