//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionSupportSystem.DataAccessLayer.DataCreationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PairCriteria
    {
        public long id { get; set; }
        public long firstCriteriaId { get; set; }
        public long secondCriteriaId { get; set; }
        public double minRangeValue { get; set; }
        public double middleRangeValue { get; set; }
        public double maxRangeValue { get; set; }
    
        public virtual Criteria firstCriteria { get; set; }
        public virtual Criteria secondCriteria { get; set; }
    }
}
