//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionSupportSystem.DataAccessLayer.DataCreationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PairAlternative
    {
        public long id { get; set; }
        public long firstAlternativeId { get; set; }
        public long secondAlternativeId { get; set; }
        public long criteriaId { get; set; }
        public double minRangeValue { get; set; }
        public double middleRangeValue { get; set; }
        public double maxRangeValue { get; set; }
    
        public virtual Alternative firstAlternative { get; set; }
        public virtual Alternative secondAlternative { get; set; }
        public virtual Criteria criteria { get; set; }
    }
}
